compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

supportedArchitectures:
  os:
    - current
    - darwin
    - linux
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
    - musl

yarnPath: .yarn/releases/yarn-4.5.0.cjs
